language: python
os: linux
sudo: false

python:
  - '3.7'
env:
  - APOLLO_VERISON=2
  - APOLLO_VERISON=3

services:
  - docker

before_install:
  - pip install -U pip flake8 setuptools nose
  - python setup.py install

jobs:
  include:
    - stage: lint
      install:
        - pip install -U pip flake8
      script:
        - flake8 apollo --ignore=E501,W503 --exclude=arrow/commands/,scripts/

    - stage: test
      script:
        - if [ ${APOLLO_VERSION} == "2" ]; then export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/apollo.yml ; ./bootstrap_apollo.sh --docker2 ; fi;
        - if [ ${APOLLO_VERSION} == "3" ]; then export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/docker-apollo3-arrow.yml ; ./bootstrap_apollo.sh --docker3 ; fi;
        - python setup.py nosetests

#    - stage: deploy
#      install: skip
#      script: echo "Deploying to Pypi"
#      deploy:
#        provider: pypi
#        username: erasche
#        password:
#          secure: odHEB/SR+BddRI0qFJU3d57w0J3OjIHLLmoxv5rH46/R6WDBJ1Dqp85rbIEfjTsLEG6bd04kdNSUh/kFB1O8TAOjthixHYNij5qgAfIXYpCTCfoFd/+sqtLl2UddlkO/d895+QV3nEDWSSZuAbys3kBvzVBqlcZ1fpcBr7dyynUJ2hzjD/rq2F475ClKNAA6ICarYZErSu6RHprLieQpUYWKfielXjhMBtWwrJcrwYsdi2bIhdirGpddB5Qi8MZ8BtSpDojpSWBu5O59LLpJhO9JLktO/TfdOSRzZwCAthqbxGvGgpp9x4D5IpTL19uiY5D2jF13nvhYs5Vf2i75FoAGplJ9snOkYE52JJ3/XtqOv22no9P7wSIUJkA/P3DabzqfxlcTdjLtS2v53YehNHL/1ZtrI95y3d37aw9UUKv9KZzz3ostGoAoCIV9YMzK9NrOPeBRRYFzqsrZcOy2yugAawuH/78w9dproeoO/9gFakoLzbObq1gLX10cdnHW4K1qLBE+tasTrXjE5OCa+svBhIMgvk8c+vX/ISvci/pvc1St+prek40vxZi7dIfoqK+iyoACn9RsrdwjSm4Woe058L99wd0FnLaMiLrQNe3h/AHZDQJ5EXGXI0l5egAlJHX/CfxcFekEZS66merlvFUtqsuetd+XIWmAroZq9g0=
#        on:
#          tags: true
#          distributions: "sdist bdist_wheel"
#          repo: galaxy-genome-annotation/python-apollo

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/dd56606ea08bece475e7
    on_success: change
    on_failure: always
    on_start: never

stages:
  - lint
  - test
  - deploy
